---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insureme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insureme
  template:
    metadata:
      labels:
        app: insureme
    spec:
      containers:
        - name: insurance
          image: docker push pranadock/demohealthcarerana:1.0
          ports:
            - containerPort: 8084
          env:
            - name: PORT
              value: "8084"
---
apiVersion: v1
kind: Service
metadata:
  name: insureme
spec:
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: insureme
